server:
  port: 8081

# 默认的profile为offline，其他环境通过指定启动参数使用不同的profile，比如：
#   线下环境：java -jar my-spring-boot.jar --spring.profiles.active=offline
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=online
spring:
  profiles:
    active: offline
  application:
    name: backend-demo

---
# 线下环境
spring:
  profiles: offline
  zipkin:
    percentage: 1.0
    enabled: true
  rabbitmq:
    host: 120.27.34.1
    port: 5672
    username: test
    password: test001
    virtual-host: /test

---
# 线上环境
spring:
  profiles: online
  zipkin:
    percentage: 1.0
    enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test001
    virtual-host: /test